# my global config
global:
  scrape_interval:     300s
  evaluation_interval: 300s 

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
     - targets: ['10.10.10.10:9090']

  - job_name: 'blackbox'
    file_sd_configs:
    - files:
      - '/mydata/blackbox/*.yml'
      refresh_interval: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 11.11.11.11:9115
